# Generated by Django 4.2.5 on 2023-10-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGaleriaWeb', '0006_obraarte_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraarte',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGaleriaWeb.galeria'),
        ),
    ]
